INSERT INTO EMPLOYEE (EMAIL, FNAME, LNAME, SALARY, TITLE)
VALUES ('test@gmail.com', 'testFirst','testLast',100.0,'student');

INSERT INTO SECURITY_ROLE (ROLENAME)
VALUES ('USER_ROLE');

INSERT INTO SECURITY_ROLE (ROLENAME)
VALUES ('ADMIN_ROLE');

INSERT INTO SECURITY_USER (PWHASH, USERNAME, EMP_ID)
VALUES ('PBKDF2WithHmacSHA256:2048:41t5a8XB+6IEOCY94QXyPzTggenSR35to5+Q0tMsurk=:OVITfPmhfOm0FzEzG91b02u7lLse+uJsNyEdYrMRImM=
','user1',1);

INSERT INTO SECURITY_USER (PWHASH, USERNAME)
VALUES ('PBKDF2WithHmacSHA256:2048:zAebhiRmSZw/0yo09pfzb0Hm1AKSE9wRTkjR93ThUUw=:dvbQmDF4EtwMZOxGgukZo2KwF4vubPtQOnN0OFJOZqg=
','admin');


INSERT INTO SECURITY_USER_SECURITY_ROLE (ROLE_ID, USER_ID)
VALUES (1,1);

INSERT INTO SECURITY_USER_SECURITY_ROLE (ROLE_ID, USER_ID)
VALUES (2,1);